spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.102.211.48:3306/mango?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: gylang
    password: Gylang123456.
#    dbcp2:
#      validation-query: SELECT 1
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: true
#    hikari:
#      max-lifetime: 1800000
  redis:
    host: 47.102.211.48
    password: gylang123456
    port: 6379
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    open-in-view: true
  jackson:
    default-property-inclusion: non_null

login:
  user:
    maxNum: 2
    sessionPrefix: gylang_sression_
    user2SeesionPrefix: gylang_user_2_session_
